---
title: "&#39;Catch&#39; block never reached; &lt;exception&gt; handled above in the same &#39;Try&#39; statement"

ms.date: "2015-07-20"
ms.prod: .net


ms.technology: 
  - "devlang-visual-basic"

ms.topic: "article"
f1_keywords: 
  - "bc42031"
  - "vbc42031"
helpviewer_keywords: 
  - "BC42031"
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
caps.latest.revision: 10
author: dotnet-bot
ms.author: dotnetcontent

translation.priority.ht: 
  - "de-de"
  - "es-es"
  - "fr-fr"
  - "it-it"
  - "ja-jp"
  - "ko-kr"
  - "ru-ru"
  - "zh-cn"
  - "zh-tw"
translation.priority.mt: 
  - "cs-cz"
  - "pl-pl"
  - "pt-br"
  - "tr-tr"
---
# &#39;Catch&#39; block never reached; &lt;exception&gt; handled above in the same &#39;Try&#39; statement
A `Catch` block in the code cannot be reached because it is handled in a preceding `Try` block.  
  
 By default, this message is a warning. For more information about hiding warnings or treating warnings as errors, please see [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic)  
  
 **Error ID:** BC42031  
  
## To correct this error  
  
-   Remove the redundant statement.  
  
## See Also  
 [How to: Catch an Exception in Visual Basic](http://msdn.microsoft.com/en-us/f3063c89-d2bf-49b1-91b5-b87edfb18b95)   
 [How to: Test Code with a Tryâ€¦Catch Block in Visual Basic](http://msdn.microsoft.com/en-us/8368e205-ed73-4185-a247-af84fb4fafa9)   
 [How to: Filter Errors in a Catch Block in Visual Basic](http://msdn.microsoft.com/en-us/85964d0a-56e7-4301-a96e-5eaea23b7b9b)   
 [Walkthrough: Structured Exception Handling (Visual Basic)](http://msdn.microsoft.com/en-us/440da655-4b32-490b-8b16-bfe46f41fa76)   
 [Try...Catch...Finally Statement](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
